import { PLATFORM_META, calculatePriceSuggestions, calculateProfit, draftAsText, generateDraft, inventoryToCsv, inventoryToJson, normalizeInventory, normalizeItem, resolvePlatformSelection, validateItem } from './core.js';

const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
const STORAGE_KEY = 'snaplist:inventory:v2';
const SETTINGS_KEY = 'snaplist:settings:v2';
const STATUS_LABELS = { draft: '下書き', listed: '出品中', sold: '売却済み', hold: '保留' };
const FORM_FIELDS = ['name','brand','category','condition','color','size','model','accessories','flaws','shippingMethod','shippingDays','price','cost','feeRate','shippingCost','notes'];
const state = { photos: [], current: normalizeItem({ price: 5000, feeRate: 10, platforms: ['mercari'] }), inventory: loadInventory(), platforms: ['mercari'], variants: {} };
const yen = (value) => new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(Number(value||0));
const escapeHtml = (value) => String(value??'').replace(/[&<>'"]/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));

function notify(message){const toast=$('#toast');toast.textContent=message;toast.hidden=false;clearTimeout(notify.timer);notify.timer=setTimeout(()=>{toast.hidden=true;},2800);}
function loadInventory(){try{return normalizeInventory(localStorage.getItem(STORAGE_KEY)||'[]');}catch{return[];}}
function persistInventory(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state.inventory));$('#navCount').textContent=String(state.inventory.length);}catch{notify('保存容量を超えました。写真または商品を減らしてください。');}}
function getSettings(){try{return{apiBase:'',allowImageUpload:false,...JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')};}catch{return{apiBase:'',allowImageUpload:false};}}
function saveSettings(){const settings={apiBase:$('#apiBase').value.trim().replace(/\/$/,''),allowImageUpload:$('#allowImageUpload').checked};localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));updateModeDisplay();notify('設定を保存しました。');}
function updateModeDisplay(){const settings=getSettings();const api=Boolean(settings.apiBase&&settings.allowImageUpload);$('#modeLabel').textContent=api?'API解析モード':'端末内デモモード';$('#modeDot').classList.toggle('api',api);$('#photoPrivacyText').textContent=api?`解析時に写真を ${settings.apiBase} へ送信します。送信同意は設定で解除できます。`:'API未接続時は写真を外部送信せず、端末内のデモ生成だけを使います。';$('#networkLabel').textContent=navigator.onLine?'オンライン':'オフライン';}
function setView(view){$('#composerView').hidden=view!=='composer';$('#inventoryView').hidden=view!=='inventory';$$('.nav-tab[data-view]').forEach((button)=>button.classList.toggle('active',button.dataset.view===view));if(view==='inventory')renderInventory();window.scrollTo({top:0,behavior:'smooth'});}
function setStep(step){$$('.stepper li').forEach((item)=>item.classList.toggle('active',Number(item.dataset.step)<=step));}

async function compressPhoto(file){const dataUrl=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});const image=await new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=dataUrl;});const max=900;const scale=Math.min(1,max/Math.max(image.width,image.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));canvas.getContext('2d',{alpha:false}).drawImage(image,0,0,canvas.width,canvas.height);return{id:crypto.randomUUID(),name:file.name||'photo.jpg',thumbnail:canvas.toDataURL('image/jpeg',.76)};}
async function addPhotos(files){const remaining=Math.max(0,4-state.photos.length);const accepted=[...files].filter((file)=>file.type.startsWith('image/')).slice(0,remaining);if(!accepted.length)return notify(remaining?'画像ファイルを選択してください。':'写真は最大4枚です。');$('#analyzeBtn').disabled=true;$('#analyzeBtn').textContent='画像を圧縮しています…';try{state.photos.push(...await Promise.all(accepted.map(compressPhoto)));renderPhotos();}catch{notify('画像を読み込めませんでした。別の写真をお試しください。');}finally{$('#analyzeBtn').disabled=state.photos.length===0;$('#analyzeBtn').innerHTML='写真から出品案を作る <span aria-hidden="true">→</span>';}}
function renderPhotos(){$('#photoGrid').innerHTML=state.photos.map((photo,index)=>`<figure class="photo-thumb"><img src="${photo.thumbnail}" alt="商品写真 ${index+1}"><button type="button" data-remove-photo="${index}" aria-label="商品写真 ${index+1} を削除">×</button><figcaption>${index+1}</figcaption></figure>`).join('');$('#analyzeBtn').disabled=state.photos.length===0;$('#dropzone').classList.toggle('has-photos',state.photos.length>0);}
function demoAnalysis(){const hint=$('#productHint').value.trim();const fileName=state.photos[0]?.name?.replace(/\.[^.]+$/,'').replace(/[_-]+/g,' ');return normalizeItem({...state.current,photos:state.photos,name:hint||fileName||'写真の商品（名称要確認）',brand:'要確認',category:'その他',condition:$('#quickCondition').value,model:'要確認',accessories:'写真に写っているものがすべてです',price:state.current.price||5000,source:'demo'});}
async function analyze(){if(!state.photos.length)return notify('写真を追加してください。');$('#analyzeBtn').disabled=true;$('#analyzeBtn').textContent='出品案を作成しています…';const settings=getSettings();let item;if(settings.apiBase&&settings.allowImageUpload){try{const response=await fetch(`${settings.apiBase}/api/analyze`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image_data_url:state.photos[0].thumbnail,file_name:state.photos[0].name,product_hint:$('#productHint').value.trim(),condition:$('#quickCondition').value})});if(!response.ok)throw new Error('analysis failed');const result=await response.json();item=normalizeItem({...state.current,photos:state.photos,source:'api',name:result.title||$('#productHint').value,brand:result.brand,category:result.category,condition:result.condition,price:result.price?.recommended||state.current.price||5000,model:result.attributes?.型番||'要確認',accessories:result.attributes?.付属品||'写真に写っているものがすべてです',flaws:Array.isArray(result.warnings)?result.warnings.join(' '):''});notify('API解析結果を読み込みました。必ず内容を確認してください。');}catch{item=demoAnalysis();notify('APIへ接続できなかったため、端末内デモ生成へ切り替えました。');}}else{item=demoAnalysis();notify('端末内デモ生成で出品案を作成しました。');}state.current=item;state.platforms=item.platforms.length?item.platforms:['mercari'];state.variants={};fillForm(item);$('#analysisSource').textContent=item.source==='api'?'API解析・要確認':'デモ生成・要確認';$('#editorSection').hidden=false;$('#platformSection').hidden=false;updatePlatformUi();renderCalculations();renderDrafts();setStep(3);$('#editorSection').scrollIntoView({behavior:'smooth',block:'start'});$('#analyzeBtn').disabled=false;$('#analyzeBtn').innerHTML='写真から出品案を作り直す <span aria-hidden="true">→</span>';}

function fillForm(item){const form=$('#listingForm');FORM_FIELDS.forEach((field)=>{if(form.elements[field])form.elements[field].value=item[field]??'';});}
function readForm(){const form=$('#listingForm');const values=Object.fromEntries(FORM_FIELDS.map((field)=>[field,form.elements[field]?.value??'']));return normalizeItem({...state.current,...values,photos:state.photos,platforms:state.platforms,updatedAt:new Date().toISOString()});}
function renderCalculations(){state.current=readForm();const suggestions=calculatePriceSuggestions(state.current.price);$('#quickPrice').textContent=yen(suggestions.quick);$('#recommendedPrice').textContent=yen(suggestions.recommended);$('#premiumPrice').textContent=yen(suggestions.premium);const profit=calculateProfit(state.current);$('#profitSale').textContent=yen(profit.sale);$('#profitFee').textContent=`−${yen(profit.fee)}`;$('#profitCosts').textContent=`−${yen(profit.cost+profit.shippingCost)}`;$('#profitValue').textContent=yen(profit.profit);$('#profitValue').classList.toggle('negative',profit.profit<0);}
function updatePlatformUi(){const exclusive=state.platforms.includes('yahoo-fleamarket');$$('[data-platform]').forEach((input)=>{input.checked=state.platforms.includes(input.dataset.platform);input.disabled=exclusive&&input.dataset.platform!=='yahoo-fleamarket';input.closest('label').classList.toggle('selected',input.checked);input.closest('label').classList.toggle('disabled',input.disabled);});}
function renderDrafts(){state.current=readForm();state.current.drafts={};const container=$('#draftsContainer');if(!state.platforms.length){container.innerHTML='<div class="empty-card">出品先を1つ以上選択してください。</div>';return;}container.innerHTML=state.platforms.map((platform)=>{const draft=generateDraft(state.current,platform,state.variants[platform]||0);state.current.drafts[platform]=draft;return`<article class="draft-card" data-draft-card="${platform}"><div class="draft-head"><div><span class="platform-mark">${escapeHtml(draft.platformLabel.slice(0,1))}</span><div><h3>${escapeHtml(draft.platformLabel)}</h3><small>確認用下書き・自動投稿なし</small></div></div><button class="ghost small" type="button" data-action="regenerate" data-platform="${platform}">再生成</button></div><div class="draft-field"><div><span>タイトル</span><small>${draft.title.length}/40</small></div><p>${escapeHtml(draft.title)}</p><button type="button" data-action="copy-title" data-platform="${platform}">コピー</button></div><div class="draft-field description"><div><span>説明文</span><small>${draft.description.length}文字</small></div><pre>${escapeHtml(draft.description)}</pre><button type="button" data-action="copy-description" data-platform="${platform}">コピー</button></div><dl class="draft-meta"><div><dt>価格</dt><dd>${yen(draft.price)}</dd></div><div><dt>状態</dt><dd>${escapeHtml(draft.condition)}</dd></div><div><dt>配送</dt><dd>${escapeHtml(draft.shipping)}</dd></div></dl><button class="secondary wide" type="button" data-action="copy-all" data-platform="${platform}">この販路の下書きをすべてコピー</button></article>`;}).join('');}
async function copyText(value){try{await navigator.clipboard.writeText(value);}catch{const textarea=document.createElement('textarea');textarea.value=value;document.body.append(textarea);textarea.select();document.execCommand('copy');textarea.remove();}notify('クリップボードへコピーしました。');}
function validateAndShow(item){const errors=validateItem(item);const box=$('#validationErrors');box.hidden=errors.length===0;box.innerHTML=errors.length?`<strong>入力を確認してください</strong><span>${errors.map(escapeHtml).join('<br>')}</span>`:'';return errors.length===0;}
function saveCurrent(){const item=readForm();if(!validateAndShow(item))return;item.platforms=[...state.platforms];item.photos=[...state.photos];item.drafts=Object.fromEntries(state.platforms.map((platform)=>[platform,generateDraft(item,platform,state.variants[platform]||0)]));const index=state.inventory.findIndex((entry)=>entry.id===item.id);if(index>=0)state.inventory[index]=item;else state.inventory.unshift(item);state.inventory=normalizeInventory(state.inventory);state.current=item;persistInventory();setStep(4);notify('商品台帳へ保存しました。');}
function startNew(){state.photos=[];state.platforms=['mercari'];state.variants={};state.current=normalizeItem({price:5000,feeRate:10,platforms:['mercari']});$('#productHint').value='';$('#quickCondition').value='目立った傷や汚れなし';$('#editorSection').hidden=true;$('#platformSection').hidden=true;$('#validationErrors').hidden=true;renderPhotos();setStep(1);setView('composer');}
function statusOptions(current){return Object.entries(STATUS_LABELS).map(([value,label])=>`<option value="${value}" ${value===current?'selected':''}>${label}</option>`).join('');}
function renderInventory(){const query=$('#inventorySearch').value.trim().toLowerCase();const filter=$('#statusFilter').value;const counts=Object.fromEntries(Object.keys(STATUS_LABELS).map((status)=>[status,state.inventory.filter((item)=>item.status===status).length]));$('#inventoryStats').innerHTML=Object.entries(STATUS_LABELS).map(([status,label])=>`<div><span>${label}</span><strong>${counts[status]}</strong></div>`).join('');const items=state.inventory.filter((item)=>{const haystack=`${item.name} ${item.brand} ${item.model}`.toLowerCase();return(!query||haystack.includes(query))&&(filter==='all'||item.status===filter);});$('#inventoryList').innerHTML=items.length?items.map((item)=>`<article class="inventory-item" data-item-id="${escapeHtml(item.id)}"><div class="inventory-thumb">${item.photos[0]?.thumbnail?`<img src="${item.photos[0].thumbnail}" alt="">`:'<span>写真なし</span>'}</div><div class="inventory-main"><div class="inventory-title"><div><h3>${escapeHtml(item.name||'商品名未入力')}</h3><p>${escapeHtml(item.brand)} · ${escapeHtml(item.model)}</p></div><strong>${yen(item.price)}</strong></div><div class="inventory-tags">${item.platforms.map((platform)=>`<span>${escapeHtml(PLATFORM_META[platform]?.label||platform)}</span>`).join('')}<small>更新 ${new Date(item.updatedAt).toLocaleDateString('ja-JP')}</small></div></div><div class="inventory-actions"><select data-action="status" aria-label="${escapeHtml(item.name)}の状態">${statusOptions(item.status)}</select><button type="button" data-action="edit">編集</button><button type="button" data-action="duplicate">複製</button><button type="button" data-action="delete" class="danger-button">削除</button></div></article>`).join(''):'<div class="empty-card">条件に一致する商品はありません。</div>';$('#navCount').textContent=String(state.inventory.length);}
function editItem(item){state.current=normalizeItem(item);state.photos=[...state.current.photos];state.platforms=[...state.current.platforms];state.variants={};renderPhotos();fillForm(state.current);updatePlatformUi();renderCalculations();renderDrafts();$('#editorSection').hidden=false;$('#platformSection').hidden=false;$('#analysisSource').textContent=state.current.source==='api'?'API解析・要確認':'保存済みデータ';setStep(3);setView('composer');}
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function importInventory(file){try{const imported=normalizeInventory(await file.text());if(!imported.length)throw new Error('empty');const merged=new Map(state.inventory.map((item)=>[item.id,item]));imported.forEach((item)=>merged.set(item.id,item));state.inventory=normalizeInventory([...merged.values()]);persistInventory();renderInventory();notify(`${imported.length}件を読み込みました。`);}catch{notify('JSONを読み込めませんでした。形式を確認してください。');}}

$('#photoInput').addEventListener('change',(event)=>addPhotos(event.target.files));
$('#photoGrid').addEventListener('click',(event)=>{const button=event.target.closest('[data-remove-photo]');if(!button)return;state.photos.splice(Number(button.dataset.removePhoto),1);renderPhotos();});
$('#clearPhotosBtn').addEventListener('click',()=>{state.photos=[];renderPhotos();});
['dragenter','dragover'].forEach((name)=>$('#dropzone').addEventListener(name,(event)=>{event.preventDefault();$('#dropzone').classList.add('dragging');}));
['dragleave','drop'].forEach((name)=>$('#dropzone').addEventListener(name,(event)=>{event.preventDefault();$('#dropzone').classList.remove('dragging');}));
$('#dropzone').addEventListener('drop',(event)=>addPhotos(event.dataTransfer.files));
$('#analyzeBtn').addEventListener('click',analyze);
$('#listingForm').addEventListener('input',()=>{renderCalculations();renderDrafts();});
$$('[data-price-kind]').forEach((button)=>button.addEventListener('click',()=>{const suggestions=calculatePriceSuggestions(readForm().price);$('#listingForm').elements.price.value=suggestions[button.dataset.priceKind];renderCalculations();renderDrafts();}));
$('#platformChoices').addEventListener('change',async(event)=>{const input=event.target.closest('[data-platform]');if(!input)return;const outcome=resolvePlatformSelection(state.platforms,input.dataset.platform,input.checked);if(outcome.requiresConfirmation){input.checked=false;$('#exclusiveDialog').showModal();await new Promise((resolve)=>$('#exclusiveDialog').addEventListener('close',resolve,{once:true}));if($('#exclusiveDialog').returnValue==='confirm')state.platforms=['yahoo-fleamarket'];}else{state.platforms=outcome.selected;if(outcome.removedExclusive)notify('Yahoo!フリマ専用モードを解除しました。');}updatePlatformUi();renderDrafts();});
$('#draftsContainer').addEventListener('click',(event)=>{const button=event.target.closest('[data-action]');if(!button)return;const platform=button.dataset.platform;const draft=state.current.drafts[platform];if(!draft)return;if(button.dataset.action==='regenerate'){state.variants[platform]=(state.variants[platform]||0)+1;return renderDrafts();}if(button.dataset.action==='copy-title')copyText(draft.title);if(button.dataset.action==='copy-description')copyText(draft.description);if(button.dataset.action==='copy-all')copyText(draftAsText(draft));});
$('#saveItemBtn').addEventListener('click',saveCurrent);$('#exportCurrentBtn').addEventListener('click',()=>download('snaplist-item.json',inventoryToJson([readForm()]),'application/json'));$('#newItemBtn').addEventListener('click',startNew);$('#inventorySearch').addEventListener('input',renderInventory);$('#statusFilter').addEventListener('change',renderInventory);
$('#inventoryList').addEventListener('change',(event)=>{const select=event.target.closest('[data-action="status"]');if(!select)return;const item=state.inventory.find((entry)=>entry.id===select.closest('[data-item-id]').dataset.itemId);if(item){item.status=select.value;item.updatedAt=new Date().toISOString();persistInventory();renderInventory();}});
$('#inventoryList').addEventListener('click',(event)=>{const button=event.target.closest('button[data-action]');if(!button)return;const id=button.closest('[data-item-id]').dataset.itemId;const item=state.inventory.find((entry)=>entry.id===id);if(!item)return;if(button.dataset.action==='edit')editItem(item);if(button.dataset.action==='duplicate'){const copy=normalizeItem({...item,id:crypto.randomUUID(),name:`${item.name}（複製）`,status:'draft',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});state.inventory.unshift(copy);persistInventory();renderInventory();notify('商品を複製しました。');}if(button.dataset.action==='delete'&&confirm(`「${item.name}」を商品台帳から削除しますか？`)){state.inventory=state.inventory.filter((entry)=>entry.id!==id);persistInventory();renderInventory();notify('商品を削除しました。');}});
$('#exportJsonBtn').addEventListener('click',()=>download('snaplist-inventory.json',inventoryToJson(state.inventory),'application/json'));$('#exportCsvBtn').addEventListener('click',()=>download('snaplist-inventory.csv',inventoryToCsv(state.inventory),'text/csv;charset=utf-8'));$('#importInput').addEventListener('change',(event)=>{const[file]=event.target.files;if(file)importInventory(file);event.target.value='';});
$$('.nav-tab[data-view]').forEach((button)=>button.addEventListener('click',()=>setView(button.dataset.view)));$('[data-view-link="composer"]').addEventListener('click',(event)=>{event.preventDefault();setView('composer');});$('#settingsBtn').addEventListener('click',()=>{const settings=getSettings();$('#apiBase').value=settings.apiBase;$('#allowImageUpload').checked=settings.allowImageUpload;$('#settingsDialog').showModal();});$('#saveSettings').addEventListener('click',saveSettings);window.addEventListener('online',updateModeDisplay);window.addEventListener('offline',updateModeDisplay);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
persistInventory();renderPhotos();updateModeDisplay();updatePlatformUi();
