const $=s=>document.querySelector(s);let imageData=null;let draft=null;const yen=n=>new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(n);const toast=m=>{const e=$('#toast');e.textContent=m;e.hidden=false;setTimeout(()=>e.hidden=true,2600)};

$('#photoInput').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;imageData=await readFile(file);$('#preview').src=imageData;$('#preview').hidden=false;$('#emptyState').hidden=true;$('#analyzeBtn').disabled=false;$('#status').textContent='解析できます'});
function readFile(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
function demoDraft(){const hint=$('#productHint').value.trim()||'撮影した商品';const condition=$('#condition').value;const prices=[4200,4800,5100,5600];const median=4950;return{title:`${hint} 中古 美品 動作確認済み`.slice(0,80),description:`ご覧いただきありがとうございます。${hint}の出品です。状態は「${condition}」として確認しています。写真に写っているものが付属品のすべてです。中古品のため、写真で状態をご確認のうえご購入ください。丁寧に梱包し、追跡可能な方法で発送します。`,brand:'要確認',category:'その他',condition,attributes:{動作:'確認済み',付属品:'写真参照'},tags:['中古','即購入可','匿名配送'],price:{low:4200,median,high:5600,quick_sale:4300,recommended:4900,premium:5800,confidence:.75},samples:prices.map((p,i)=>({platform:['メルカリ参考','Yahoo!参考','eBay参考','自社販売履歴'][i],title:`${hint} 同等品`,price:p})),warnings:['デモ解析です。型番、真贋、傷、付属品は出品前に確認してください。']}}
async function analyze(){setBusy(true);const api=localStorage.getItem('apiBase')||'';try{if(!api)throw new Error('demo');const res=await fetch(`${api.replace(/\/$/,'')}/api/analyze`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image_data_url:imageData,file_name:$('#photoInput').files[0]?.name||'photo.jpg',product_hint:$('#productHint').value,condition:$('#condition').value})});if(!res.ok)throw new Error(`API ${res.status}`);draft=await res.json();toast('AI解析が完了しました')}catch{draft=demoDraft();toast('ブラウザ内デモ解析で生成しました')}renderDraft();setBusy(false)}
function setBusy(on){$('#analyzeBtn').disabled=on;$('#analyzeBtn span:first-child').textContent=on?'解析しています…':'AIで商品を解析する';$('#status').textContent=on?'画像と相場を解析中':'編集できます'}
function renderDraft(){$('#resultEmpty').hidden=true;$('#result').hidden=false;$('#rangePrice').textContent=`${yen(draft.price.low)}〜${yen(draft.price.high)}`;$('#recommendedPrice').textContent=yen(draft.price.recommended);$('#quickPrice').textContent=yen(draft.price.quick_sale);$('#title').value=draft.title;$('#description').value=draft.description;$('#brand').value=draft.brand;$('#category').value=draft.category;$('#resultCondition').value=draft.condition;$('#samples').innerHTML=draft.samples.map(s=>`<div class="sample"><span>${escapeHtml(s.platform)}<br>${escapeHtml(s.title)}</span><strong>${yen(s.price)}</strong></div>`).join('')}
function syncDraft(){draft.title=$('#title').value;draft.description=$('#description').value;draft.brand=$('#brand').value;draft.category=$('#category').value;draft.condition=$('#resultCondition').value}
function selectedPlatforms(){return [...document.querySelectorAll('.platforms input:checked')].map(x=>x.value)}
async function publish(){syncDraft();const platforms=selectedPlatforms();if(!platforms.length)return toast('出品先を選択してください');const api=localStorage.getItem('apiBase')||'';let results;try{if(!api)throw new Error('demo');const res=await fetch(`${api.replace(/\/$/,'')}/api/publish`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({draft,platforms,image_urls:[]})});if(!res.ok)throw new Error('publish');results=await res.json()}catch{const id=crypto.randomUUID();localStorage.setItem(`listing:${id}`,JSON.stringify({draft,platforms,imageData,createdAt:new Date().toISOString()}));results=platforms.map(p=>({platform:p,mode:p==='own-store'?'published':'draft',listing_id:id,message:p==='own-store'?'ブラウザ内の自社ストアへ保存しました。':'公式API未接続のため入力済み下書きを作成しました。'}))}$('#publishResults').innerHTML=results.map(r=>`<div class="publish-result ${r.mode}"><strong>${escapeHtml(r.platform)}</strong> — ${escapeHtml(r.message)}</div>`).join('');toast('出品準備が完了しました')}
function exportData(){syncDraft();const payload={draft,platforms:selectedPlatforms(),created_at:new Date().toISOString()};download('snaplist-listing.json',JSON.stringify(payload,null,2),'application/json');const csv=['platform,title,price,condition,description',...payload.platforms.map(p=>[p,draft.title,draft.price.recommended,draft.condition,draft.description].map(csvCell).join(','))].join('\n');setTimeout(()=>download('snaplist-listing.csv','\ufeff'+csv,'text/csv'),250)}
function csvCell(v){return `"${String(v).replaceAll('"','""')}"`}function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$('#analyzeBtn').addEventListener('click',analyze);$('#publishBtn').addEventListener('click',publish);$('#exportBtn').addEventListener('click',exportData);$('#settingsBtn').addEventListener('click',()=>{$('#apiBase').value=localStorage.getItem('apiBase')||'';$('#settingsDialog').showModal()});$('#saveSettings').addEventListener('click',()=>{localStorage.setItem('apiBase',$('#apiBase').value.trim());toast('API設定を保存しました')});if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
